--
-- Create Schema Script 
--   Database Version          : 11.2.0.1.0 
--   Database Compatible Level : 11.2.0.0.0 
--   Script Compatible Level   : 11.2.0.0.0 
--   Toad Version              : 12.1.0.22 
--   DB Connect String         : 10.118.255.5:1521/ORCL5 
--   Schema                    : BIOMART_USER 
--   Script Created by         : BIOMART_USER 
--   Script Created at         : 7/17/2015 3:46:22 PM 
--   Physical Location         :  
--   Notes                     :  
--

-- Object Counts: 
--   Indexes: 1         Columns: 1          
--   Object Privileges: 1 
--   Procedures: 2      Lines of Code: 144 
--   Sequences: 2 
--   Synonyms: 332 
--   Tables: 9          Columns: 165        Constraints: 9      
--   Types: 2 


--
-- CONCEPT_CD_TAB  (Type) 
--
CREATE OR REPLACE TYPE                "CONCEPT_CD_TAB"                                          IS TABLE OF VARCHAR2(50)
/

--
-- PATIENTS_TAB  (Type) 
--
CREATE OR REPLACE TYPE                "PATIENTS_TAB"                                          IS TABLE OF NUMBER(10,0)
/

--
-- I2B2_GSE10846  (Table) 
--
CREATE TABLE I2B2_GSE10846
(
  C_HLEVEL            NUMBER(22),
  C_FULLNAME          VARCHAR2(700 BYTE)        NOT NULL,
  C_NAME              VARCHAR2(2000 BYTE),
  C_SYNONYM_CD        CHAR(1 BYTE),
  C_VISUALATTRIBUTES  CHAR(3 BYTE),
  C_TOTALNUM          NUMBER(22),
  C_BASECODE          VARCHAR2(50 BYTE),
  C_METADATAXML       CLOB,
  C_FACTTABLECOLUMN   VARCHAR2(50 BYTE),
  C_TABLENAME         VARCHAR2(50 BYTE),
  C_COLUMNNAME        VARCHAR2(50 BYTE),
  C_COLUMNDATATYPE    VARCHAR2(50 BYTE),
  C_OPERATOR          VARCHAR2(10 BYTE),
  C_DIMCODE           VARCHAR2(700 BYTE),
  C_COMMENT           CLOB,
  C_TOOLTIP           VARCHAR2(900 BYTE),
  UPDATE_DATE         DATE                      NOT NULL,
  DOWNLOAD_DATE       DATE,
  IMPORT_DATE         DATE,
  SOURCESYSTEM_CD     VARCHAR2(50 BYTE),
  VALUETYPE_CD        VARCHAR2(50 BYTE),
  I2B2_ID             NUMBER(22),
  M_APPLIED_PATH      VARCHAR2(700 BYTE),
  M_EXCLUSION_CD      VARCHAR2(25 BYTE),
  C_PATH              VARCHAR2(700 BYTE),
  C_SYMBOL            VARCHAR2(50 BYTE)
);


--
-- I2B2_GSE20685  (Table) 
--
CREATE TABLE I2B2_GSE20685
(
  C_HLEVEL            NUMBER(22),
  C_FULLNAME          VARCHAR2(700 BYTE)        NOT NULL,
  C_NAME              VARCHAR2(2000 BYTE),
  C_SYNONYM_CD        CHAR(1 BYTE),
  C_VISUALATTRIBUTES  CHAR(3 BYTE),
  C_TOTALNUM          NUMBER(22),
  C_BASECODE          VARCHAR2(50 BYTE),
  C_METADATAXML       CLOB,
  C_FACTTABLECOLUMN   VARCHAR2(50 BYTE),
  C_TABLENAME         VARCHAR2(50 BYTE),
  C_COLUMNNAME        VARCHAR2(50 BYTE),
  C_COLUMNDATATYPE    VARCHAR2(50 BYTE),
  C_OPERATOR          VARCHAR2(10 BYTE),
  C_DIMCODE           VARCHAR2(700 BYTE),
  C_COMMENT           CLOB,
  C_TOOLTIP           VARCHAR2(900 BYTE),
  UPDATE_DATE         DATE                      NOT NULL,
  DOWNLOAD_DATE       DATE,
  IMPORT_DATE         DATE,
  SOURCESYSTEM_CD     VARCHAR2(50 BYTE),
  VALUETYPE_CD        VARCHAR2(50 BYTE),
  I2B2_ID             NUMBER(22),
  M_APPLIED_PATH      VARCHAR2(700 BYTE),
  M_EXCLUSION_CD      VARCHAR2(25 BYTE),
  C_PATH              VARCHAR2(700 BYTE),
  C_SYMBOL            VARCHAR2(50 BYTE)
);


--
-- I2B2_SECURE_GSE10846  (Table) 
--
CREATE TABLE I2B2_SECURE_GSE10846
(
  C_HLEVEL            NUMBER(22),
  C_FULLNAME          VARCHAR2(900 BYTE)        NOT NULL,
  C_NAME              VARCHAR2(2000 BYTE),
  C_SYNONYM_CD        CHAR(1 BYTE),
  C_VISUALATTRIBUTES  CHAR(3 BYTE),
  C_TOTALNUM          NUMBER(22),
  C_BASECODE          VARCHAR2(450 BYTE),
  C_METADATAXML       CLOB,
  C_FACTTABLECOLUMN   VARCHAR2(50 BYTE),
  C_TABLENAME         VARCHAR2(50 BYTE),
  C_COLUMNNAME        VARCHAR2(50 BYTE),
  C_COLUMNDATATYPE    VARCHAR2(50 BYTE),
  C_OPERATOR          VARCHAR2(10 BYTE),
  C_DIMCODE           VARCHAR2(900 BYTE),
  C_COMMENT           CLOB,
  C_TOOLTIP           VARCHAR2(900 BYTE),
  UPDATE_DATE         DATE,
  DOWNLOAD_DATE       DATE,
  IMPORT_DATE         DATE,
  SOURCESYSTEM_CD     VARCHAR2(50 BYTE),
  VALUETYPE_CD        VARCHAR2(50 BYTE),
  SECURE_OBJ_TOKEN    VARCHAR2(50 BYTE),
  M_APPLIED_PATH      VARCHAR2(700 BYTE),
  M_EXCLUSION_CD      VARCHAR2(25 BYTE)
);


--
-- I2B2_SECURE_GSE20685  (Table) 
--
CREATE TABLE I2B2_SECURE_GSE20685
(
  C_HLEVEL            NUMBER(22),
  C_FULLNAME          VARCHAR2(900 BYTE)        NOT NULL,
  C_NAME              VARCHAR2(2000 BYTE),
  C_SYNONYM_CD        CHAR(1 BYTE),
  C_VISUALATTRIBUTES  CHAR(3 BYTE),
  C_TOTALNUM          NUMBER(22),
  C_BASECODE          VARCHAR2(450 BYTE),
  C_METADATAXML       CLOB,
  C_FACTTABLECOLUMN   VARCHAR2(50 BYTE),
  C_TABLENAME         VARCHAR2(50 BYTE),
  C_COLUMNNAME        VARCHAR2(50 BYTE),
  C_COLUMNDATATYPE    VARCHAR2(50 BYTE),
  C_OPERATOR          VARCHAR2(10 BYTE),
  C_DIMCODE           VARCHAR2(900 BYTE),
  C_COMMENT           CLOB,
  C_TOOLTIP           VARCHAR2(900 BYTE),
  UPDATE_DATE         DATE,
  DOWNLOAD_DATE       DATE,
  IMPORT_DATE         DATE,
  SOURCESYSTEM_CD     VARCHAR2(50 BYTE),
  VALUETYPE_CD        VARCHAR2(50 BYTE),
  SECURE_OBJ_TOKEN    VARCHAR2(50 BYTE),
  M_APPLIED_PATH      VARCHAR2(700 BYTE),
  M_EXCLUSION_CD      VARCHAR2(25 BYTE)
);


--
-- IOE_TEMP_OBJ_REG2  (Table) 
--
CREATE TABLE IOE_TEMP_OBJ_REG2
(
  OBJECT_SCHEMA             VARCHAR2(32 BYTE),
  OBJECT_NAME               VARCHAR2(32 BYTE),
  OBJECT_TYPE               VARCHAR2(64 BYTE),
  KDE_USERNAME              VARCHAR2(64 BYTE),
  KDE_SESSION               VARCHAR2(255 BYTE),
  OBJECT_CREATED_TIMESTAMP  TIMESTAMP(0)
);


--
-- KDE_TEMP_OBJ_REG3  (Table) 
--
CREATE TABLE KDE_TEMP_OBJ_REG3
(
  OBJECT_SCHEMA             VARCHAR2(32 BYTE),
  OBJECT_NAME               VARCHAR2(32 BYTE),
  OBJECT_TYPE               VARCHAR2(64 BYTE),
  KDE_USERNAME              VARCHAR2(64 BYTE),
  KDE_SESSION               VARCHAR2(255 BYTE),
  OBJECT_CREATED_TIMESTAMP  CHAR(15 BYTE)
);


--
-- T  (Table) 
--
CREATE TABLE T
(
  TRIAL  CLOB
);


--
-- TM_SAVED_ANALYSIS  (Table) 
--
CREATE TABLE TM_SAVED_ANALYSIS
(
  TM_SAVED_ANALYSIS_ID  NUMBER(38)              NOT NULL,
  SUBSET_ID             NUMBER(38),
  ANALYSIS_FILE         BLOB,
  ANALYSIS_NM           VARCHAR2(250 BYTE),
  ANALYSIS_DESCR        VARCHAR2(4000 BYTE),
  CRETD_BY              VARCHAR2(80 BYTE),
  UPDTD_BY              VARCHAR2(80 BYTE),
  RQST_ID               VARCHAR2(80 BYTE),
  TENANT_ID             NUMBER(38),
  SRC_SYS_NM            VARCHAR2(80 BYTE),
  CRETN_DT              DATE                    NOT NULL,
  UPDT_DT               DATE,
  EFFCTV_STRT_DT        DATE,
  EFFCTV_END_DT         DATE,
  CRRNT_FLG             CHAR(1 BYTE),
  DELETE_FLG            CHAR(1 BYTE),
  CONSTRAINT TM_SAVED_ANALYSIS_P1
  PRIMARY KEY
  (TM_SAVED_ANALYSIS_ID)
  ENABLE VALIDATE
);


--
-- TOAD_PLAN_TABLE  (Table) 
--
CREATE TABLE TOAD_PLAN_TABLE
(
  STATEMENT_ID       VARCHAR2(30 BYTE),
  PLAN_ID            NUMBER,
  TIMESTAMP          DATE,
  REMARKS            VARCHAR2(4000 BYTE),
  OPERATION          VARCHAR2(30 BYTE),
  OPTIONS            VARCHAR2(255 BYTE),
  OBJECT_NODE        VARCHAR2(128 BYTE),
  OBJECT_OWNER       VARCHAR2(30 BYTE),
  OBJECT_NAME        VARCHAR2(30 BYTE),
  OBJECT_ALIAS       VARCHAR2(65 BYTE),
  OBJECT_INSTANCE    INTEGER,
  OBJECT_TYPE        VARCHAR2(30 BYTE),
  OPTIMIZER          VARCHAR2(255 BYTE),
  SEARCH_COLUMNS     NUMBER,
  ID                 INTEGER,
  PARENT_ID          INTEGER,
  DEPTH              INTEGER,
  POSITION           INTEGER,
  COST               INTEGER,
  CARDINALITY        INTEGER,
  BYTES              INTEGER,
  OTHER_TAG          VARCHAR2(255 BYTE),
  PARTITION_START    VARCHAR2(255 BYTE),
  PARTITION_STOP     VARCHAR2(255 BYTE),
  PARTITION_ID       INTEGER,
  OTHER              LONG,
  DISTRIBUTION       VARCHAR2(30 BYTE),
  CPU_COST           INTEGER,
  IO_COST            INTEGER,
  TEMP_SPACE         INTEGER,
  ACCESS_PREDICATES  VARCHAR2(4000 BYTE),
  FILTER_PREDICATES  VARCHAR2(4000 BYTE),
  PROJECTION         VARCHAR2(4000 BYTE),
  TIME               INTEGER,
  QBLOCK_NAME        VARCHAR2(30 BYTE),
  OTHER_XML          CLOB
);


--
-- SEQ_SEARCH_AUTH_USER_ID  (Sequence) 
--
CREATE SEQUENCE SEQ_SEARCH_AUTH_USER_ID
  START WITH 701145780
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--
-- SEQ_TM_SAVED_ANALYSIS_ID  (Sequence) 
--
CREATE SEQUENCE SEQ_TM_SAVED_ANALYSIS_ID
  START WITH 421
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;




--
-- CREATE_FILE_FROM_QUERY  (Procedure) 
--
CREATE OR REPLACE procedure create_file_from_query( p_query in varchar2,
                                  p_dir   in varchar2,
                                  p_filename in varchar2 )
IS
     l_output        utl_file.file_type;
     l_theCursor     INTEGER DEFAULT dbms_sql.open_cursor;
     l_columnValue   VARCHAR2(4000);
     l_status        INTEGER;
     l_query         VARCHAR2(1000);
     l_colCnt        NUMBER := 0;
     l_separator     VARCHAR2(1);
     l_descTbl       dbms_sql.desc_tab2;
BEGIN
     l_output := utl_file.fopen( p_dir, p_filename, 'w', 32767);
     EXECUTE IMMEDIATE 'alter session set nls_date_format=''dd-mon-yyyy hh24:mi:ss'' ';
     
     dbms_sql.parse(  l_theCursor,  p_query, dbms_sql.NATIVE );
     dbms_sql.describe_columns2( l_theCursor, l_colCnt, l_descTbl );
     for i in 1 .. l_colCnt loop
         utl_file.put( l_output, l_separator || '"' || l_descTbl(i).col_name|| '"' );
         dbms_output.put_line('Column Type :: ' || l_descTbl(i).col_type);
         --col_type = 112 : 112 is the # for CLOB data-type
         IF (l_desctbl(i).col_type = 112) THEN
            dbms_sql.define_column( l_theCursor, i, l_columnValue, 4000000000);
         else
            dbms_sql.define_column( l_theCursor, i, l_columnValue, 4000 );
         END IF;
         l_separator := ',';
     end loop;
     utl_file.new_line( l_output );
     l_status := dbms_sql.execute(l_theCursor);
     while ( dbms_sql.fetch_rows(l_theCursor) > 0 ) loop
         l_separator := '';
         FOR i IN 1 .. l_colCnt loop
             dbms_sql.column_value( l_theCursor, i, l_columnValue );
             IF (l_desctbl(i).col_type = 112) THEN
                l_columnValue := rtrim(rtrim(dbms_lob.substr(replace(l_columnValue,'"','""'))));
             END IF;
             utl_file.put( l_output, l_separator || l_columnValue );
             l_separator := ',';
         end loop;
         utl_file.new_line( l_output );
     end loop;
     dbms_sql.close_cursor(l_theCursor);
     utl_file.fclose( l_output );
     execute immediate 'alter session set nls_date_format=''dd-MON-yy'' ';
exception
    when utl_file.invalid_path then
       raise_application_error(-20100,'Invalid Path');
    when utl_file.invalid_mode then
       raise_application_error(-20101,'Invalid Mode');
    when utl_file.invalid_operation then
       raise_application_error(-20102,'Invalid Operation');
    when utl_file.invalid_filehandle then
       raise_application_error(-20103,'Invalid FileHandle');
    when utl_file.write_error then
       raise_application_error(-20104,'Write Error');
    when utl_file.read_error then
       raise_application_error(-20105,'Read Error');
    when utl_file.internal_error then
       raise_application_error(-20106,'Internal Error');
    when others then
         utl_file.fclose( l_output );
         execute immediate 'alter session set nls_date_format=''dd-MON-yy'' ';
         raise;
end;
 
 
 
 
 
 
/

--
-- ADD_ONTOLOGY_NODE  (Synonym) 
--
CREATE SYNONYM ADD_ONTOLOGY_NODE FOR I2B2METADATA.ADD_ONTOLOGY_NODE;


--
-- AM_DATA_UID  (Synonym) 
--
CREATE SYNONYM AM_DATA_UID FOR AMAPP.AM_DATA_UID;


--
-- AM_TAG_ASSOCIATION  (Synonym) 
--
CREATE SYNONYM AM_TAG_ASSOCIATION FOR AMAPP.AM_TAG_ASSOCIATION;


--
-- AM_TAG_DISPLAY_VW  (Synonym) 
--
CREATE SYNONYM AM_TAG_DISPLAY_VW FOR AMAPP.AM_TAG_DISPLAY_VW;


--
-- AM_TAG_ITEM  (Synonym) 
--
CREATE SYNONYM AM_TAG_ITEM FOR AMAPP.AM_TAG_ITEM;


--
-- AM_TAG_TEMPLATE  (Synonym) 
--
CREATE SYNONYM AM_TAG_TEMPLATE FOR AMAPP.AM_TAG_TEMPLATE;


--
-- AM_TAG_TEMPLATE_ASSOCIATION  (Synonym) 
--
CREATE SYNONYM AM_TAG_TEMPLATE_ASSOCIATION FOR AMAPP.AM_TAG_TEMPLATE_ASSOCIATION;


--
-- AM_TAG_VALUE  (Synonym) 
--
CREATE SYNONYM AM_TAG_VALUE FOR AMAPP.AM_TAG_VALUE;


--
-- ASYNC_JOB  (Synonym) 
--
CREATE SYNONYM ASYNC_JOB FOR I2B2DEMODATA.ASYNC_JOB;


--
-- BIO_AD_HOC_PROPERTY  (Synonym) 
--
CREATE SYNONYM BIO_AD_HOC_PROPERTY FOR BIOMART.BIO_AD_HOC_PROPERTY;


--
-- BIO_ANALYSIS_ATTRIBUTE  (Synonym) 
--
CREATE SYNONYM BIO_ANALYSIS_ATTRIBUTE FOR BIOMART.BIO_ANALYSIS_ATTRIBUTE;


--
-- BIO_ANALYSIS_ATTRIBUTE_LINEAGE  (Synonym) 
--
CREATE SYNONYM BIO_ANALYSIS_ATTRIBUTE_LINEAGE FOR BIOMART.BIO_ANALYSIS_ATTRIBUTE_LINEAGE;


--
-- BIO_ASSAY  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY FOR BIOMART.BIO_ASSAY;


--
-- BIO_ASSAY_ANALYSIS  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_ANALYSIS FOR BIOMART.BIO_ASSAY_ANALYSIS;


--
-- BIO_ASSAY_ANALYSIS_DATA  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_ANALYSIS_DATA FOR BIOMART.BIO_ASSAY_ANALYSIS_DATA;


--
-- BIO_ASSAY_ANALYSIS_DATA_TEA  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_ANALYSIS_DATA_TEA FOR BIOMART.BIO_ASSAY_ANALYSIS_DATA_TEA;


--
-- BIO_ASSAY_ANALYSIS_EXT  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_ANALYSIS_EXT FOR BIOMART.BIO_ASSAY_ANALYSIS_EXT;


--
-- BIO_ASSAY_DATA  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_DATA FOR BIOMART.BIO_ASSAY_DATA;


--
-- BIO_ASSAY_DATASET  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_DATASET FOR BIOMART.BIO_ASSAY_DATASET;


--
-- BIO_ASSAY_DATA_ANNOTATION  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_DATA_ANNOTATION FOR BIOMART.BIO_ASSAY_DATA_ANNOTATION;


--
-- BIO_ASSAY_DATA_STATS  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_DATA_STATS FOR BIOMART.BIO_ASSAY_DATA_STATS;


--
-- BIO_ASSAY_DATA_STATS_SEQ  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_DATA_STATS_SEQ FOR BIOMART.BIO_ASSAY_DATA_STATS_SEQ;


--
-- BIO_ASSAY_DATA_TEA_TOP50_MV  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_DATA_TEA_TOP50_MV FOR BIOMART.BIO_ASSAY_DATA_TEA_TOP50_MV;


--
-- BIO_ASSAY_FEATURE_GROUP  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_FEATURE_GROUP FOR BIOMART.BIO_ASSAY_FEATURE_GROUP;


--
-- BIO_ASSAY_PLATFORM  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_PLATFORM FOR BIOMART.BIO_ASSAY_PLATFORM;


--
-- BIO_ASSAY_SAMPLE  (Synonym) 
--
CREATE SYNONYM BIO_ASSAY_SAMPLE FOR BIOMART.BIO_ASSAY_SAMPLE;


--
-- BIO_ASY_ANALYSIS_DATASET  (Synonym) 
--
CREATE SYNONYM BIO_ASY_ANALYSIS_DATASET FOR BIOMART.BIO_ASY_ANALYSIS_DATASET;


--
-- BIO_ASY_ANALYSIS_PLTFM  (Synonym) 
--
CREATE SYNONYM BIO_ASY_ANALYSIS_PLTFM FOR BIOMART.BIO_ASY_ANALYSIS_PLTFM;


--
-- BIO_ASY_DATA_STATS_ALL  (Synonym) 
--
CREATE SYNONYM BIO_ASY_DATA_STATS_ALL FOR BIOMART.BIO_ASY_DATA_STATS_ALL;


--
-- BIO_CELL_LINE  (Synonym) 
--
CREATE SYNONYM BIO_CELL_LINE FOR BIOMART.BIO_CELL_LINE;


--
-- BIO_CGDCP_DATA  (Synonym) 
--
CREATE SYNONYM BIO_CGDCP_DATA FOR BIOMART.BIO_CGDCP_DATA;


--
-- BIO_CLINC_TRIAL_ATTR  (Synonym) 
--
CREATE SYNONYM BIO_CLINC_TRIAL_ATTR FOR BIOMART.BIO_CLINC_TRIAL_ATTR;


--
-- BIO_CLINC_TRIAL_PT_GROUP  (Synonym) 
--
CREATE SYNONYM BIO_CLINC_TRIAL_PT_GROUP FOR BIOMART.BIO_CLINC_TRIAL_PT_GROUP;


--
-- BIO_CLINC_TRIAL_TIME_PT  (Synonym) 
--
CREATE SYNONYM BIO_CLINC_TRIAL_TIME_PT FOR BIOMART.BIO_CLINC_TRIAL_TIME_PT;


--
-- BIO_CLINICAL_TRIAL  (Synonym) 
--
CREATE SYNONYM BIO_CLINICAL_TRIAL FOR BIOMART.BIO_CLINICAL_TRIAL;


--
-- BIO_CLINICAL_TRIAL_DESIGN  (Synonym) 
--
CREATE SYNONYM BIO_CLINICAL_TRIAL_DESIGN FOR BIOMART.BIO_CLINICAL_TRIAL_DESIGN;


--
-- BIO_COMPOUND  (Synonym) 
--
CREATE SYNONYM BIO_COMPOUND FOR BIOMART.BIO_COMPOUND;


--
-- BIO_CONCEPT_CODE  (Synonym) 
--
CREATE SYNONYM BIO_CONCEPT_CODE FOR BIOMART.BIO_CONCEPT_CODE;


--
-- BIO_CONTENT  (Synonym) 
--
CREATE SYNONYM BIO_CONTENT FOR BIOMART.BIO_CONTENT;


--
-- BIO_CONTENT_REFERENCE  (Synonym) 
--
CREATE SYNONYM BIO_CONTENT_REFERENCE FOR BIOMART.BIO_CONTENT_REFERENCE;


--
-- BIO_CONTENT_REPOSITORY  (Synonym) 
--
CREATE SYNONYM BIO_CONTENT_REPOSITORY FOR BIOMART.BIO_CONTENT_REPOSITORY;


--
-- BIO_CURATED_DATA  (Synonym) 
--
CREATE SYNONYM BIO_CURATED_DATA FOR BIOMART.BIO_CURATED_DATA;


--
-- BIO_CURATION_DATASET  (Synonym) 
--
CREATE SYNONYM BIO_CURATION_DATASET FOR BIOMART.BIO_CURATION_DATASET;


--
-- BIO_DATA_ATTRIBUTE  (Synonym) 
--
CREATE SYNONYM BIO_DATA_ATTRIBUTE FOR BIOMART.BIO_DATA_ATTRIBUTE;


--
-- BIO_DATA_COMPOUND  (Synonym) 
--
CREATE SYNONYM BIO_DATA_COMPOUND FOR BIOMART.BIO_DATA_COMPOUND;


--
-- BIO_DATA_CORRELATION  (Synonym) 
--
CREATE SYNONYM BIO_DATA_CORRELATION FOR BIOMART.BIO_DATA_CORRELATION;


--
-- BIO_DATA_CORREL_DESCR  (Synonym) 
--
CREATE SYNONYM BIO_DATA_CORREL_DESCR FOR BIOMART.BIO_DATA_CORREL_DESCR;


--
-- BIO_DATA_DISEASE  (Synonym) 
--
CREATE SYNONYM BIO_DATA_DISEASE FOR BIOMART.BIO_DATA_DISEASE;


--
-- BIO_DATA_EXT_CODE  (Synonym) 
--
CREATE SYNONYM BIO_DATA_EXT_CODE FOR BIOMART.BIO_DATA_EXT_CODE;


--
-- BIO_DATA_LITERATURE  (Synonym) 
--
CREATE SYNONYM BIO_DATA_LITERATURE FOR BIOMART.BIO_DATA_LITERATURE;


--
-- BIO_DATA_OBSERVATION  (Synonym) 
--
CREATE SYNONYM BIO_DATA_OBSERVATION FOR BIOMART.BIO_DATA_OBSERVATION;


--
-- BIO_DATA_OMIC_MARKER  (Synonym) 
--
CREATE SYNONYM BIO_DATA_OMIC_MARKER FOR BIOMART.BIO_DATA_OMIC_MARKER;


--
-- BIO_DATA_TAXONOMY  (Synonym) 
--
CREATE SYNONYM BIO_DATA_TAXONOMY FOR BIOMART.BIO_DATA_TAXONOMY;


--
-- BIO_DATA_UID  (Synonym) 
--
CREATE SYNONYM BIO_DATA_UID FOR BIOMART.BIO_DATA_UID;


--
-- BIO_DISEASE  (Synonym) 
--
CREATE SYNONYM BIO_DISEASE FOR BIOMART.BIO_DISEASE;


--
-- BIO_EXPERIMENT  (Synonym) 
--
CREATE SYNONYM BIO_EXPERIMENT FOR BIOMART.BIO_EXPERIMENT;


--
-- BIO_LIT_ALT_DATA  (Synonym) 
--
CREATE SYNONYM BIO_LIT_ALT_DATA FOR BIOMART.BIO_LIT_ALT_DATA;


--
-- BIO_LIT_AMD_DATA  (Synonym) 
--
CREATE SYNONYM BIO_LIT_AMD_DATA FOR BIOMART.BIO_LIT_AMD_DATA;


--
-- BIO_LIT_INH_DATA  (Synonym) 
--
CREATE SYNONYM BIO_LIT_INH_DATA FOR BIOMART.BIO_LIT_INH_DATA;


--
-- BIO_LIT_INT_DATA  (Synonym) 
--
CREATE SYNONYM BIO_LIT_INT_DATA FOR BIOMART.BIO_LIT_INT_DATA;


--
-- BIO_LIT_INT_MODEL_MV  (Synonym) 
--
CREATE SYNONYM BIO_LIT_INT_MODEL_MV FOR BIOMART.BIO_LIT_INT_MODEL_MV;


--
-- BIO_LIT_MODEL_DATA  (Synonym) 
--
CREATE SYNONYM BIO_LIT_MODEL_DATA FOR BIOMART.BIO_LIT_MODEL_DATA;


--
-- BIO_LIT_PE_DATA  (Synonym) 
--
CREATE SYNONYM BIO_LIT_PE_DATA FOR BIOMART.BIO_LIT_PE_DATA;


--
-- BIO_LIT_REF_DATA  (Synonym) 
--
CREATE SYNONYM BIO_LIT_REF_DATA FOR BIOMART.BIO_LIT_REF_DATA;


--
-- BIO_LIT_SUM_DATA  (Synonym) 
--
CREATE SYNONYM BIO_LIT_SUM_DATA FOR BIOMART.BIO_LIT_SUM_DATA;


--
-- BIO_MARKER  (Synonym) 
--
CREATE SYNONYM BIO_MARKER FOR BIOMART.BIO_MARKER;


--
-- BIO_MARKER_CORREL_MV  (Synonym) 
--
CREATE SYNONYM BIO_MARKER_CORREL_MV FOR BIOMART.BIO_MARKER_CORREL_MV;


--
-- BIO_MARKER_EXP_ANALYSIS_MV  (Synonym) 
--
CREATE SYNONYM BIO_MARKER_EXP_ANALYSIS_MV FOR BIOMART.BIO_MARKER_EXP_ANALYSIS_MV;


--
-- BIO_OBSERVATION  (Synonym) 
--
CREATE SYNONYM BIO_OBSERVATION FOR BIOMART.BIO_OBSERVATION;


--
-- BIO_PATIENT  (Synonym) 
--
CREATE SYNONYM BIO_PATIENT FOR BIOMART.BIO_PATIENT;


--
-- BIO_PATIENT_EVENT  (Synonym) 
--
CREATE SYNONYM BIO_PATIENT_EVENT FOR BIOMART.BIO_PATIENT_EVENT;


--
-- BIO_PATIENT_EVENT_ATTR  (Synonym) 
--
CREATE SYNONYM BIO_PATIENT_EVENT_ATTR FOR BIOMART.BIO_PATIENT_EVENT_ATTR;


--
-- BIO_SAMPLE  (Synonym) 
--
CREATE SYNONYM BIO_SAMPLE FOR BIOMART.BIO_SAMPLE;


--
-- BIO_SPECIES_ORGANISM  (Synonym) 
--
CREATE SYNONYM BIO_SPECIES_ORGANISM FOR BIOMART.BIO_SPECIES_ORGANISM;


--
-- BIO_STATS_EXP_MARKER  (Synonym) 
--
CREATE SYNONYM BIO_STATS_EXP_MARKER FOR BIOMART.BIO_STATS_EXP_MARKER;


--
-- BIO_SUBJECT  (Synonym) 
--
CREATE SYNONYM BIO_SUBJECT FOR BIOMART.BIO_SUBJECT;


--
-- BIO_TAXONOMY  (Synonym) 
--
CREATE SYNONYM BIO_TAXONOMY FOR BIOMART.BIO_TAXONOMY;


--
-- CODE_LOOKUP  (Synonym) 
--
CREATE SYNONYM CODE_LOOKUP FOR I2B2DEMODATA.CODE_LOOKUP;


--
-- CONCEPT_COUNTS  (Synonym) 
--
CREATE SYNONYM CONCEPT_COUNTS FOR I2B2DEMODATA.CONCEPT_COUNTS;


--
-- CONCEPT_DIMENSION  (Synonym) 
--
CREATE SYNONYM CONCEPT_DIMENSION FOR I2B2DEMODATA.CONCEPT_DIMENSION;


--
-- CONCEPT_ID  (Synonym) 
--
CREATE SYNONYM CONCEPT_ID FOR I2B2DEMODATA.CONCEPT_ID;


--
-- COUNTER  (Synonym) 
--
CREATE SYNONYM COUNTER FOR I2B2DEMODATA.COUNTER;


--
-- CRC_ANALYSIS_JOB  (Synonym) 
--
CREATE SYNONYM CRC_ANALYSIS_JOB FOR I2B2HIVE.CRC_ANALYSIS_JOB;


--
-- CRC_DB_LOOKUP  (Synonym) 
--
CREATE SYNONYM CRC_DB_LOOKUP FOR I2B2DEMODATA.CRC_DB_LOOKUP;


--
-- CREATE_TEMP_CONCEPT_TABLE  (Synonym) 
--
CREATE SYNONYM CREATE_TEMP_CONCEPT_TABLE FOR I2B2DEMODATA.CREATE_TEMP_CONCEPT_TABLE;


--
-- CREATE_TEMP_EID_TABLE  (Synonym) 
--
CREATE SYNONYM CREATE_TEMP_EID_TABLE FOR I2B2DEMODATA.CREATE_TEMP_EID_TABLE;


--
-- CREATE_TEMP_PATIENT_TABLE  (Synonym) 
--
CREATE SYNONYM CREATE_TEMP_PATIENT_TABLE FOR I2B2DEMODATA.CREATE_TEMP_PATIENT_TABLE;


--
-- CREATE_TEMP_PID_TABLE  (Synonym) 
--
CREATE SYNONYM CREATE_TEMP_PID_TABLE FOR I2B2DEMODATA.CREATE_TEMP_PID_TABLE;


--
-- CREATE_TEMP_PROVIDER_TABLE  (Synonym) 
--
CREATE SYNONYM CREATE_TEMP_PROVIDER_TABLE FOR I2B2DEMODATA.CREATE_TEMP_PROVIDER_TABLE;


--
-- CREATE_TEMP_TABLE  (Synonym) 
--
CREATE SYNONYM CREATE_TEMP_TABLE FOR I2B2DEMODATA.CREATE_TEMP_TABLE;


--
-- CREATE_TEMP_VISIT_TABLE  (Synonym) 
--
CREATE SYNONYM CREATE_TEMP_VISIT_TABLE FOR I2B2DEMODATA.CREATE_TEMP_VISIT_TABLE;


--
-- CTD2_CLIN_INHIB_EFFECT  (Synonym) 
--
CREATE SYNONYM CTD2_CLIN_INHIB_EFFECT FOR BIOMART.CTD2_CLIN_INHIB_EFFECT;


--
-- CTD2_DISEASE  (Synonym) 
--
CREATE SYNONYM CTD2_DISEASE FOR BIOMART.CTD2_DISEASE;


--
-- CTD2_INHIB_DETAILS  (Synonym) 
--
CREATE SYNONYM CTD2_INHIB_DETAILS FOR BIOMART.CTD2_INHIB_DETAILS;


--
-- CTD2_STUDY  (Synonym) 
--
CREATE SYNONYM CTD2_STUDY FOR BIOMART.CTD2_STUDY;


--
-- CTD2_TRIAL_DETAILS  (Synonym) 
--
CREATE SYNONYM CTD2_TRIAL_DETAILS FOR BIOMART.CTD2_TRIAL_DETAILS;


--
-- CTD_ALLOWED_MEDS_TREATMENT  (Synonym) 
--
CREATE SYNONYM CTD_ALLOWED_MEDS_TREATMENT FOR BIOMART.CTD_ALLOWED_MEDS_TREATMENT;


--
-- CTD_ARM_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_ARM_VIEW FOR BIOMART.CTD_ARM_VIEW;


--
-- CTD_BIOMARKER  (Synonym) 
--
CREATE SYNONYM CTD_BIOMARKER FOR BIOMART.CTD_BIOMARKER;


--
-- CTD_BIOMARKER_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_BIOMARKER_VIEW FOR BIOMART.CTD_BIOMARKER_VIEW;


--
-- CTD_CELL_INFO_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_CELL_INFO_VIEW FOR BIOMART.CTD_CELL_INFO_VIEW;


--
-- CTD_CLINICAL_CHARS_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_CLINICAL_CHARS_VIEW FOR BIOMART.CTD_CLINICAL_CHARS_VIEW;


--
-- CTD_DISEASE  (Synonym) 
--
CREATE SYNONYM CTD_DISEASE FOR BIOMART.CTD_DISEASE;


--
-- CTD_DRUG_EFFECTS_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_DRUG_EFFECTS_VIEW FOR BIOMART.CTD_DRUG_EFFECTS_VIEW;


--
-- CTD_DRUG_INHIB  (Synonym) 
--
CREATE SYNONYM CTD_DRUG_INHIB FOR BIOMART.CTD_DRUG_INHIB;


--
-- CTD_DRUG_INHIBITOR_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_DRUG_INHIBITOR_VIEW FOR BIOMART.CTD_DRUG_INHIBITOR_VIEW;


--
-- CTD_EVENTS_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_EVENTS_VIEW FOR BIOMART.CTD_EVENTS_VIEW;


--
-- CTD_EXPERIMENTS_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_EXPERIMENTS_VIEW FOR BIOMART.CTD_EXPERIMENTS_VIEW;


--
-- CTD_EXPR_AFTER_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_EXPR_AFTER_VIEW FOR BIOMART.CTD_EXPR_AFTER_VIEW;


--
-- CTD_EXPR_BASELINE_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_EXPR_BASELINE_VIEW FOR BIOMART.CTD_EXPR_BASELINE_VIEW;


--
-- CTD_EXPR_BIO_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_EXPR_BIO_VIEW FOR BIOMART.CTD_EXPR_BIO_VIEW;


--
-- CTD_EXPR_SOURCE_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_EXPR_SOURCE_VIEW FOR BIOMART.CTD_EXPR_SOURCE_VIEW;


--
-- CTD_FULL  (Synonym) 
--
CREATE SYNONYM CTD_FULL FOR BIOMART.CTD_FULL;


--
-- CTD_FULL_CLINICAL_ENDPTS_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_FULL_CLINICAL_ENDPTS_VIEW FOR BIOMART.CTD_FULL_CLINICAL_ENDPTS_VIEW;


--
-- CTD_FULL_SEARCH_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_FULL_SEARCH_VIEW FOR BIOMART.CTD_FULL_SEARCH_VIEW;


--
-- CTD_INCLUSION_CRITERIA  (Synonym) 
--
CREATE SYNONYM CTD_INCLUSION_CRITERIA FOR BIOMART.CTD_INCLUSION_CRITERIA;


--
-- CTD_PRIMARY_ENDPTS  (Synonym) 
--
CREATE SYNONYM CTD_PRIMARY_ENDPTS FOR BIOMART.CTD_PRIMARY_ENDPTS;


--
-- CTD_PRIMARY_ENDPTS_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_PRIMARY_ENDPTS_VIEW FOR BIOMART.CTD_PRIMARY_ENDPTS_VIEW;


--
-- CTD_PRIOR_MED_USE_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_PRIOR_MED_USE_VIEW FOR BIOMART.CTD_PRIOR_MED_USE_VIEW;


--
-- CTD_PULMONARY_PATH_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_PULMONARY_PATH_VIEW FOR BIOMART.CTD_PULMONARY_PATH_VIEW;


--
-- CTD_QUANT_PARAMS_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_QUANT_PARAMS_VIEW FOR BIOMART.CTD_QUANT_PARAMS_VIEW;


--
-- CTD_REFERENCE_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_REFERENCE_VIEW FOR BIOMART.CTD_REFERENCE_VIEW;


--
-- CTD_RUNIN_THERAPIES_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_RUNIN_THERAPIES_VIEW FOR BIOMART.CTD_RUNIN_THERAPIES_VIEW;


--
-- CTD_SECONDARY_ENDPTS_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_SECONDARY_ENDPTS_VIEW FOR BIOMART.CTD_SECONDARY_ENDPTS_VIEW;


--
-- CTD_SEC_ENDPTS  (Synonym) 
--
CREATE SYNONYM CTD_SEC_ENDPTS FOR BIOMART.CTD_SEC_ENDPTS;


--
-- CTD_STATS_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_STATS_VIEW FOR BIOMART.CTD_STATS_VIEW;


--
-- CTD_STUDY  (Synonym) 
--
CREATE SYNONYM CTD_STUDY FOR BIOMART.CTD_STUDY;


--
-- CTD_STUDY_DETAILS_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_STUDY_DETAILS_VIEW FOR BIOMART.CTD_STUDY_DETAILS_VIEW;


--
-- CTD_TD_DESIGN_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_TD_DESIGN_VIEW FOR BIOMART.CTD_TD_DESIGN_VIEW;


--
-- CTD_TD_EXCL_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_TD_EXCL_VIEW FOR BIOMART.CTD_TD_EXCL_VIEW;


--
-- CTD_TD_INCLUSION_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_TD_INCLUSION_VIEW FOR BIOMART.CTD_TD_INCLUSION_VIEW;


--
-- CTD_TD_SMOKER_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_TD_SMOKER_VIEW FOR BIOMART.CTD_TD_SMOKER_VIEW;


--
-- CTD_TD_SPONSOR_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_TD_SPONSOR_VIEW FOR BIOMART.CTD_TD_SPONSOR_VIEW;


--
-- CTD_TD_STATUS_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_TD_STATUS_VIEW FOR BIOMART.CTD_TD_STATUS_VIEW;


--
-- CTD_TREATMENT_PHASES_VIEW  (Synonym) 
--
CREATE SYNONYM CTD_TREATMENT_PHASES_VIEW FOR BIOMART.CTD_TREATMENT_PHASES_VIEW;


--
-- CUSTOM_META  (Synonym) 
--
CREATE SYNONYM CUSTOM_META FOR I2B2METADATA.CUSTOM_META;


--
-- CZ_FORM_LAYOUT  (Synonym) 
--
CREATE SYNONYM CZ_FORM_LAYOUT FOR TM_CZ.CZ_FORM_LAYOUT;


--
-- CZ_REQUIRED_UPLOAD_FIELD  (Synonym) 
--
CREATE SYNONYM CZ_REQUIRED_UPLOAD_FIELD FOR TM_CZ.CZ_REQUIRED_UPLOAD_FIELD;


--
-- DATAMART_REPORT  (Synonym) 
--
CREATE SYNONYM DATAMART_REPORT FOR I2B2DEMODATA.DATAMART_REPORT;


--
-- DEAPP_ANNOTATION  (Synonym) 
--
CREATE SYNONYM DEAPP_ANNOTATION FOR DEAPP.DEAPP_ANNOTATION;


--
-- DE_CONCEPT_VISIT  (Synonym) 
--
CREATE SYNONYM DE_CONCEPT_VISIT FOR DEAPP.DE_CONCEPT_VISIT;


--
-- DE_ENCOUNTER_LEVEL  (Synonym) 
--
CREATE SYNONYM DE_ENCOUNTER_LEVEL FOR DEAPP.DE_ENCOUNTER_LEVEL;


--
-- DE_GPL_INFO  (Synonym) 
--
CREATE SYNONYM DE_GPL_INFO FOR DEAPP.DE_GPL_INFO;


--
-- DE_MRNA_ANNOTATION  (Synonym) 
--
CREATE SYNONYM DE_MRNA_ANNOTATION FOR DEAPP.DE_MRNA_ANNOTATION;


--
-- DE_PARENT_CD_SEQ  (Synonym) 
--
CREATE SYNONYM DE_PARENT_CD_SEQ FOR DEAPP.DE_PARENT_CD_SEQ;


--
-- DE_PATHWAY  (Synonym) 
--
CREATE SYNONYM DE_PATHWAY FOR DEAPP.DE_PATHWAY;


--
-- DE_PATHWAY_GENE  (Synonym) 
--
CREATE SYNONYM DE_PATHWAY_GENE FOR DEAPP.DE_PATHWAY_GENE;


--
-- DE_RC_SNP_INFO  (Synonym) 
--
CREATE SYNONYM DE_RC_SNP_INFO FOR DEAPP.DE_RC_SNP_INFO;


--
-- DE_SAMPLE_SNP_DATA  (Synonym) 
--
CREATE SYNONYM DE_SAMPLE_SNP_DATA FOR DEAPP.DE_SAMPLE_SNP_DATA;


--
-- DE_SAVED_COMPARISON  (Synonym) 
--
CREATE SYNONYM DE_SAVED_COMPARISON FOR DEAPP.DE_SAVED_COMPARISON;


--
-- DE_SNP_CALLS_BY_GSM  (Synonym) 
--
CREATE SYNONYM DE_SNP_CALLS_BY_GSM FOR DEAPP.DE_SNP_CALLS_BY_GSM;


--
-- DE_SNP_COPY_NUMBER  (Synonym) 
--
CREATE SYNONYM DE_SNP_COPY_NUMBER FOR DEAPP.DE_SNP_COPY_NUMBER;


--
-- DE_SNP_DATA_BY_PATIENT  (Synonym) 
--
CREATE SYNONYM DE_SNP_DATA_BY_PATIENT FOR DEAPP.DE_SNP_DATA_BY_PATIENT;


--
-- DE_SNP_DATA_BY_PROBE  (Synonym) 
--
CREATE SYNONYM DE_SNP_DATA_BY_PROBE FOR DEAPP.DE_SNP_DATA_BY_PROBE;


--
-- DE_SNP_DATA_DATASET_LOC  (Synonym) 
--
CREATE SYNONYM DE_SNP_DATA_DATASET_LOC FOR DEAPP.DE_SNP_DATA_DATASET_LOC;


--
-- DE_SNP_GENE_MAP  (Synonym) 
--
CREATE SYNONYM DE_SNP_GENE_MAP FOR DEAPP.DE_SNP_GENE_MAP;


--
-- DE_SNP_INFO  (Synonym) 
--
CREATE SYNONYM DE_SNP_INFO FOR DEAPP.DE_SNP_INFO;


--
-- DE_SNP_PROBE  (Synonym) 
--
CREATE SYNONYM DE_SNP_PROBE FOR DEAPP.DE_SNP_PROBE;


--
-- DE_SNP_PROBE_SORTED_DEF  (Synonym) 
--
CREATE SYNONYM DE_SNP_PROBE_SORTED_DEF FOR DEAPP.DE_SNP_PROBE_SORTED_DEF;


--
-- DE_SNP_SUBJECT_SORTED_DEF  (Synonym) 
--
CREATE SYNONYM DE_SNP_SUBJECT_SORTED_DEF FOR DEAPP.DE_SNP_SUBJECT_SORTED_DEF;


--
-- DE_SUBJECT_MICROARRAY_DATA  (Synonym) 
--
CREATE SYNONYM DE_SUBJECT_MICROARRAY_DATA FOR DEAPP.DE_SUBJECT_MICROARRAY_DATA;


--
-- DE_SUBJECT_MICROARRAY_DATA1  (Synonym) 
--
CREATE SYNONYM DE_SUBJECT_MICROARRAY_DATA1 FOR DEAPP.DE_SUBJECT_MICROARRAY_DATA1;


--
-- DE_SUBJECT_MICROARRAY_LOGS  (Synonym) 
--
CREATE SYNONYM DE_SUBJECT_MICROARRAY_LOGS FOR DEAPP.DE_SUBJECT_MICROARRAY_LOGS;


--
-- DE_SUBJECT_MICROARRAY_MED  (Synonym) 
--
CREATE SYNONYM DE_SUBJECT_MICROARRAY_MED FOR DEAPP.DE_SUBJECT_MICROARRAY_MED;


--
-- DE_SUBJECT_PROTEIN_DATA  (Synonym) 
--
CREATE SYNONYM DE_SUBJECT_PROTEIN_DATA FOR DEAPP.DE_SUBJECT_PROTEIN_DATA;


--
-- DE_SUBJECT_RBM_DATA  (Synonym) 
--
CREATE SYNONYM DE_SUBJECT_RBM_DATA FOR DEAPP.DE_SUBJECT_RBM_DATA;


--
-- DE_SUBJECT_SAMPLE_MAPPING  (Synonym) 
--
CREATE SYNONYM DE_SUBJECT_SAMPLE_MAPPING FOR DEAPP.DE_SUBJECT_SAMPLE_MAPPING;


--
-- DE_SUBJECT_SNP_DATASET  (Synonym) 
--
CREATE SYNONYM DE_SUBJECT_SNP_DATASET FOR DEAPP.DE_SUBJECT_SNP_DATASET;


--
-- DE_VARIANT_DATASET  (Synonym) 
--
CREATE SYNONYM DE_VARIANT_DATASET FOR DEAPP.DE_VARIANT_DATASET;


--
-- DE_VARIANT_SUBJECT_DETAIL  (Synonym) 
--
CREATE SYNONYM DE_VARIANT_SUBJECT_DETAIL FOR DEAPP.DE_VARIANT_SUBJECT_DETAIL;


--
-- DE_VARIANT_SUBJECT_IDX  (Synonym) 
--
CREATE SYNONYM DE_VARIANT_SUBJECT_IDX FOR DEAPP.DE_VARIANT_SUBJECT_IDX;


--
-- DE_VARIANT_SUBJECT_SUMMARY  (Synonym) 
--
CREATE SYNONYM DE_VARIANT_SUBJECT_SUMMARY FOR DEAPP.DE_VARIANT_SUBJECT_SUMMARY;


--
-- DE_XTRIAL_CHILD_MAP  (Synonym) 
--
CREATE SYNONYM DE_XTRIAL_CHILD_MAP FOR DEAPP.DE_XTRIAL_CHILD_MAP;


--
-- DE_XTRIAL_PARENT_NAMES  (Synonym) 
--
CREATE SYNONYM DE_XTRIAL_PARENT_NAMES FOR DEAPP.DE_XTRIAL_PARENT_NAMES;


--
-- DIMLOADER  (Synonym) 
--
CREATE SYNONYM DIMLOADER FOR I2B2DEMODATA.DIMLOADER;


--
-- DR$OF_CTX_BLOB$I  (Synonym) 
--
CREATE SYNONYM DR$OF_CTX_BLOB$I FOR I2B2DEMODATA.DR$OF_CTX_BLOB$I;


--
-- DR$OF_CTX_BLOB$K  (Synonym) 
--
CREATE SYNONYM DR$OF_CTX_BLOB$K FOR I2B2DEMODATA.DR$OF_CTX_BLOB$K;


--
-- DR$OF_CTX_BLOB$N  (Synonym) 
--
CREATE SYNONYM DR$OF_CTX_BLOB$N FOR I2B2DEMODATA.DR$OF_CTX_BLOB$N;


--
-- DR$OF_CTX_BLOB$R  (Synonym) 
--
CREATE SYNONYM DR$OF_CTX_BLOB$R FOR I2B2DEMODATA.DR$OF_CTX_BLOB$R;


--
-- DUMP_TABLE_TO_CSV  (Synonym) 
--
CREATE SYNONYM DUMP_TABLE_TO_CSV FOR DEAPP.DUMP_TABLE_TO_CSV;


--
-- DX  (Synonym) 
--
CREATE SYNONYM DX FOR I2B2DEMODATA.DX;


--
-- ENCOUNTER_MAPPING  (Synonym) 
--
CREATE SYNONYM ENCOUNTER_MAPPING FOR I2B2DEMODATA.ENCOUNTER_MAPPING;


--
-- GLOBAL_TEMP_FACT_PARAM_TABLE  (Synonym) 
--
CREATE SYNONYM GLOBAL_TEMP_FACT_PARAM_TABLE FOR I2B2DEMODATA.GLOBAL_TEMP_FACT_PARAM_TABLE;


--
-- GLOBAL_TEMP_PARAM_TABLE  (Synonym) 
--
CREATE SYNONYM GLOBAL_TEMP_PARAM_TABLE FOR I2B2DEMODATA.GLOBAL_TEMP_PARAM_TABLE;


--
-- HAPLOVIEW_DATA  (Synonym) 
--
CREATE SYNONYM HAPLOVIEW_DATA FOR DEAPP.HAPLOVIEW_DATA;


--
-- HIBERNATE_SEQUENCE  (Synonym) 
--
CREATE SYNONYM HIBERNATE_SEQUENCE FOR SEARCHAPP.HIBERNATE_SEQUENCE;


--
-- HILOSEQUENCES  (Synonym) 
--
CREATE SYNONYM HILOSEQUENCES FOR I2B2HIVE.HILOSEQUENCES;


--
-- I2B2  (Synonym) 
--
CREATE SYNONYM I2B2 FOR I2B2METADATA.I2B2;


--
-- I2B2_ID_SEQ  (Synonym) 
--
CREATE SYNONYM I2B2_ID_SEQ FOR I2B2METADATA.I2B2_ID_SEQ;


--
-- I2B2_SAMPLE  (Synonym) 
--
CREATE SYNONYM I2B2_SAMPLE FOR I2B2SAMPLEDATA.I2B2_SAMPLE;


--
-- I2B2_SECURE  (Synonym) 
--
CREATE SYNONYM I2B2_SECURE FOR I2B2METADATA.I2B2_SECURE;


--
-- I2B2_TAGS  (Synonym) 
--
CREATE SYNONYM I2B2_TAGS FOR I2B2METADATA.I2B2_TAGS;


--
-- I2B2_TRIAL_NODES  (Synonym) 
--
CREATE SYNONYM I2B2_TRIAL_NODES FOR I2B2METADATA.I2B2_TRIAL_NODES;


--
-- INSERT_CONCEPT_FROMTEMP  (Synonym) 
--
CREATE SYNONYM INSERT_CONCEPT_FROMTEMP FOR I2B2DEMODATA.INSERT_CONCEPT_FROMTEMP;


--
-- INSERT_EID_MAP_FROMTEMP  (Synonym) 
--
CREATE SYNONYM INSERT_EID_MAP_FROMTEMP FOR I2B2DEMODATA.INSERT_EID_MAP_FROMTEMP;


--
-- INSERT_ENCOUNTERVISIT_FROMTEMP  (Synonym) 
--
CREATE SYNONYM INSERT_ENCOUNTERVISIT_FROMTEMP FOR I2B2DEMODATA.INSERT_ENCOUNTERVISIT_FROMTEMP;


--
-- INSERT_PATIENT_MAP_FROMTEMP  (Synonym) 
--
CREATE SYNONYM INSERT_PATIENT_MAP_FROMTEMP FOR I2B2DEMODATA.INSERT_PATIENT_MAP_FROMTEMP;


--
-- INSERT_PID_MAP_FROMTEMP  (Synonym) 
--
CREATE SYNONYM INSERT_PID_MAP_FROMTEMP FOR I2B2DEMODATA.INSERT_PID_MAP_FROMTEMP;


--
-- INSERT_PROVIDER_FROMTEMP  (Synonym) 
--
CREATE SYNONYM INSERT_PROVIDER_FROMTEMP FOR I2B2DEMODATA.INSERT_PROVIDER_FROMTEMP;


--
-- JMS_MESSAGES  (Synonym) 
--
CREATE SYNONYM JMS_MESSAGES FOR I2B2DEMODATA.JMS_MESSAGES;


--
-- JMS_ROLES  (Synonym) 
--
CREATE SYNONYM JMS_ROLES FOR I2B2HIVE.JMS_ROLES;


--
-- JMS_SUBSCRIPTIONS  (Synonym) 
--
CREATE SYNONYM JMS_SUBSCRIPTIONS FOR I2B2HIVE.JMS_SUBSCRIPTIONS;


--
-- JMS_TRANSACTIONS  (Synonym) 
--
CREATE SYNONYM JMS_TRANSACTIONS FOR I2B2HIVE.JMS_TRANSACTIONS;


--
-- JMS_USERS  (Synonym) 
--
CREATE SYNONYM JMS_USERS FOR I2B2HIVE.JMS_USERS;


--
-- LISTSIG_GENES  (Synonym) 
--
CREATE SYNONYM LISTSIG_GENES FOR SEARCHAPP.LISTSIG_GENES;


--
-- LOAD_GENE_SYNONYMS  (Synonym) 
--
CREATE SYNONYM LOAD_GENE_SYNONYMS FOR BIOMART.LOAD_GENE_SYNONYMS;


--
-- LOAD_OMIC_ASSAY_PLATFORM_DATA  (Synonym) 
--
CREATE SYNONYM LOAD_OMIC_ASSAY_PLATFORM_DATA FOR BIOMART.LOAD_OMIC_ASSAY_PLATFORM_DATA;


--
-- LOAD_PICTOR_PATHWAY_DATA  (Synonym) 
--
CREATE SYNONYM LOAD_PICTOR_PATHWAY_DATA FOR BIOMART.LOAD_PICTOR_PATHWAY_DATA;


--
-- LZ_SRC_ANALYSIS_METADATA  (Synonym) 
--
CREATE SYNONYM LZ_SRC_ANALYSIS_METADATA FOR TM_LZ.LZ_SRC_ANALYSIS_METADATA;


--
-- MASTER_QUERY_GLOBAL_TEMP  (Synonym) 
--
CREATE SYNONYM MASTER_QUERY_GLOBAL_TEMP FOR I2B2DEMODATA.MASTER_QUERY_GLOBAL_TEMP;


--
-- MICROARRAY_COMPARISON_QRY  (Synonym) 
--
CREATE SYNONYM MICROARRAY_COMPARISON_QRY FOR DEAPP.MICROARRAY_COMPARISON_QRY;


--
-- MLOG$_SEARCH_GENE_SIGNATUR  (Synonym) 
--
CREATE SYNONYM MLOG$_SEARCH_GENE_SIGNATUR FOR SEARCHAPP.MLOG$_SEARCH_GENE_SIGNATUR;


--
-- MODIFIER_DIMENSION  (Synonym) 
--
CREATE SYNONYM MODIFIER_DIMENSION FOR I2B2DEMODATA.MODIFIER_DIMENSION;


--
-- MODIFIER_DIMENSION_VIEW  (Synonym) 
--
CREATE SYNONYM MODIFIER_DIMENSION_VIEW FOR I2B2DEMODATA.MODIFIER_DIMENSION_VIEW;


--
-- MODIFIER_METADATA  (Synonym) 
--
CREATE SYNONYM MODIFIER_METADATA FOR I2B2DEMODATA.MODIFIER_METADATA;


--
-- NEWS_UPDATES  (Synonym) 
--
CREATE SYNONYM NEWS_UPDATES FOR I2B2DEMODATA.NEWS_UPDATES;


--
-- OBSERVATION_FACT  (Synonym) 
--
CREATE SYNONYM OBSERVATION_FACT FOR I2B2DEMODATA.OBSERVATION_FACT;


--
-- ONT_DB_LOOKUP  (Synonym) 
--
CREATE SYNONYM ONT_DB_LOOKUP FOR I2B2HIVE.ONT_DB_LOOKUP;


--
-- ONT_PROCESS_STATUS  (Synonym) 
--
CREATE SYNONYM ONT_PROCESS_STATUS FOR I2B2METADATA.ONT_PROCESS_STATUS;


--
-- ONT_SQ_PS_PRID  (Synonym) 
--
CREATE SYNONYM ONT_SQ_PS_PRID FOR I2B2METADATA.ONT_SQ_PS_PRID;


--
-- PATIENT_DIMENSION  (Synonym) 
--
CREATE SYNONYM PATIENT_DIMENSION FOR I2B2DEMODATA.PATIENT_DIMENSION;


--
-- PATIENT_MAPPING  (Synonym) 
--
CREATE SYNONYM PATIENT_MAPPING FOR I2B2DEMODATA.PATIENT_MAPPING;


--
-- PATIENT_TRIAL  (Synonym) 
--
CREATE SYNONYM PATIENT_TRIAL FOR I2B2DEMODATA.PATIENT_TRIAL;


--
-- PLUGIN  (Synonym) 
--
CREATE SYNONYM PLUGIN FOR SEARCHAPP.PLUGIN;


--
-- PLUGIN1  (Synonym) 
--
CREATE SYNONYM PLUGIN1 FOR SEARCHAPP.PLUGIN1;


--
-- PLUGIN_MODULE  (Synonym) 
--
CREATE SYNONYM PLUGIN_MODULE FOR SEARCHAPP.PLUGIN_MODULE;


--
-- PLUGIN_MODULE1  (Synonym) 
--
CREATE SYNONYM PLUGIN_MODULE1 FOR SEARCHAPP.PLUGIN_MODULE1;


--
-- PLUGIN_MODULE_SEQ  (Synonym) 
--
CREATE SYNONYM PLUGIN_MODULE_SEQ FOR SEARCHAPP.PLUGIN_MODULE_SEQ;


--
-- PLUGIN_SEQ  (Synonym) 
--
CREATE SYNONYM PLUGIN_SEQ FOR SEARCHAPP.PLUGIN_SEQ;


--
-- PROJECT_INFO  (Synonym) 
--
CREATE SYNONYM PROJECT_INFO FOR BIOMART.PROJECT_INFO;


--
-- PROTEIN_COMPARISON_QRY  (Synonym) 
--
CREATE SYNONYM PROTEIN_COMPARISON_QRY FOR DEAPP.PROTEIN_COMPARISON_QRY;


--
-- PROTEIN_DBL_COMP_QRY  (Synonym) 
--
CREATE SYNONYM PROTEIN_DBL_COMP_QRY FOR DEAPP.PROTEIN_DBL_COMP_QRY;


--
-- PROTOCOL_ID_SEQ  (Synonym) 
--
CREATE SYNONYM PROTOCOL_ID_SEQ FOR I2B2DEMODATA.PROTOCOL_ID_SEQ;


--
-- PROVIDER_DIMENSION  (Synonym) 
--
CREATE SYNONYM PROVIDER_DIMENSION FOR I2B2DEMODATA.PROVIDER_DIMENSION;


--
-- QT_ANALYSIS_PLUGIN  (Synonym) 
--
CREATE SYNONYM QT_ANALYSIS_PLUGIN FOR I2B2DEMODATA.QT_ANALYSIS_PLUGIN;


--
-- QT_ANALYSIS_PLUGIN_RESULT_TYPE  (Synonym) 
--
CREATE SYNONYM QT_ANALYSIS_PLUGIN_RESULT_TYPE FOR I2B2DEMODATA.QT_ANALYSIS_PLUGIN_RESULT_TYPE;


--
-- QT_BREAKDOWN_PATH  (Synonym) 
--
CREATE SYNONYM QT_BREAKDOWN_PATH FOR I2B2DEMODATA.QT_BREAKDOWN_PATH;


--
-- QT_PATIENT_ENC_COLLECTION  (Synonym) 
--
CREATE SYNONYM QT_PATIENT_ENC_COLLECTION FOR I2B2DEMODATA.QT_PATIENT_ENC_COLLECTION;


--
-- QT_PATIENT_SET_COLLECTION  (Synonym) 
--
CREATE SYNONYM QT_PATIENT_SET_COLLECTION FOR I2B2DEMODATA.QT_PATIENT_SET_COLLECTION;


--
-- QT_PDO_QUERY_MASTER  (Synonym) 
--
CREATE SYNONYM QT_PDO_QUERY_MASTER FOR I2B2DEMODATA.QT_PDO_QUERY_MASTER;


--
-- QT_PRIVILEGE  (Synonym) 
--
CREATE SYNONYM QT_PRIVILEGE FOR I2B2DEMODATA.QT_PRIVILEGE;


--
-- QT_QUERY_INSTANCE  (Synonym) 
--
CREATE SYNONYM QT_QUERY_INSTANCE FOR I2B2DEMODATA.QT_QUERY_INSTANCE;


--
-- QT_QUERY_MASTER  (Synonym) 
--
CREATE SYNONYM QT_QUERY_MASTER FOR I2B2DEMODATA.QT_QUERY_MASTER;


--
-- QT_QUERY_RESULT_INSTANCE  (Synonym) 
--
CREATE SYNONYM QT_QUERY_RESULT_INSTANCE FOR I2B2DEMODATA.QT_QUERY_RESULT_INSTANCE;


--
-- QT_QUERY_RESULT_TYPE  (Synonym) 
--
CREATE SYNONYM QT_QUERY_RESULT_TYPE FOR I2B2DEMODATA.QT_QUERY_RESULT_TYPE;


--
-- QT_QUERY_STATUS_TYPE  (Synonym) 
--
CREATE SYNONYM QT_QUERY_STATUS_TYPE FOR I2B2DEMODATA.QT_QUERY_STATUS_TYPE;


--
-- QT_SQ_PQM_QMID  (Synonym) 
--
CREATE SYNONYM QT_SQ_PQM_QMID FOR I2B2DEMODATA.QT_SQ_PQM_QMID;


--
-- QT_SQ_QI_QIID  (Synonym) 
--
CREATE SYNONYM QT_SQ_QI_QIID FOR I2B2DEMODATA.QT_SQ_QI_QIID;


--
-- QT_SQ_QM_QMID  (Synonym) 
--
CREATE SYNONYM QT_SQ_QM_QMID FOR I2B2DEMODATA.QT_SQ_QM_QMID;


--
-- QT_SQ_QPER_PECID  (Synonym) 
--
CREATE SYNONYM QT_SQ_QPER_PECID FOR I2B2DEMODATA.QT_SQ_QPER_PECID;


--
-- QT_SQ_QPR_PCID  (Synonym) 
--
CREATE SYNONYM QT_SQ_QPR_PCID FOR I2B2DEMODATA.QT_SQ_QPR_PCID;


--
-- QT_SQ_QRI_QRIID  (Synonym) 
--
CREATE SYNONYM QT_SQ_QRI_QRIID FOR I2B2DEMODATA.QT_SQ_QRI_QRIID;


--
-- QT_SQ_QR_QRID  (Synonym) 
--
CREATE SYNONYM QT_SQ_QR_QRID FOR I2B2DEMODATA.QT_SQ_QR_QRID;


--
-- QT_SQ_QS_QSID  (Synonym) 
--
CREATE SYNONYM QT_SQ_QS_QSID FOR I2B2DEMODATA.QT_SQ_QS_QSID;


--
-- QT_SQ_QXR_XRID  (Synonym) 
--
CREATE SYNONYM QT_SQ_QXR_XRID FOR I2B2DEMODATA.QT_SQ_QXR_XRID;


--
-- QT_XML_RESULT  (Synonym) 
--
CREATE SYNONYM QT_XML_RESULT FOR I2B2DEMODATA.QT_XML_RESULT;


--
-- QUERY1  (Synonym) 
--
CREATE SYNONYM QUERY1 FOR I2B2METADATA.QUERY1;


--
-- QUERY_GLOBAL_TEMP  (Synonym) 
--
CREATE SYNONYM QUERY_GLOBAL_TEMP FOR I2B2DEMODATA.QUERY_GLOBAL_TEMP;


--
-- RBM_COMPARISON_QRY  (Synonym) 
--
CREATE SYNONYM RBM_COMPARISON_QRY FOR DEAPP.RBM_COMPARISON_QRY;


--
-- RBM_DBL_COMP_QRY  (Synonym) 
--
CREATE SYNONYM RBM_DBL_COMP_QRY FOR DEAPP.RBM_DBL_COMP_QRY;


--
-- REMOVE_TEMP_TABLE  (Synonym) 
--
CREATE SYNONYM REMOVE_TEMP_TABLE FOR I2B2DEMODATA.REMOVE_TEMP_TABLE;


--
-- REPORT  (Synonym) 
--
CREATE SYNONYM REPORT FOR SEARCHAPP.REPORT;


--
-- REPORT_ITEM  (Synonym) 
--
CREATE SYNONYM REPORT_ITEM FOR SEARCHAPP.REPORT_ITEM;


--
-- SAMPLE_CATEGORIES  (Synonym) 
--
CREATE SYNONYM SAMPLE_CATEGORIES FOR I2B2DEMODATA.SAMPLE_CATEGORIES;


--
-- SCHEMES  (Synonym) 
--
CREATE SYNONYM SCHEMES FOR I2B2METADATA.SCHEMES;


--
-- SEARCH_APP_ACCESS_LOG  (Synonym) 
--
CREATE SYNONYM SEARCH_APP_ACCESS_LOG FOR SEARCHAPP.SEARCH_APP_ACCESS_LOG;


--
-- SEARCH_AUTH_GROUP  (Synonym) 
--
CREATE SYNONYM SEARCH_AUTH_GROUP FOR SEARCHAPP.SEARCH_AUTH_GROUP;


--
-- SEARCH_AUTH_GROUP_MEMBER  (Synonym) 
--
CREATE SYNONYM SEARCH_AUTH_GROUP_MEMBER FOR SEARCHAPP.SEARCH_AUTH_GROUP_MEMBER;


--
-- SEARCH_AUTH_PRINCIPAL  (Synonym) 
--
CREATE SYNONYM SEARCH_AUTH_PRINCIPAL FOR SEARCHAPP.SEARCH_AUTH_PRINCIPAL;


--
-- SEARCH_AUTH_SEC_OBJECT_ACCESS  (Synonym) 
--
CREATE SYNONYM SEARCH_AUTH_SEC_OBJECT_ACCESS FOR SEARCHAPP.SEARCH_AUTH_SEC_OBJECT_ACCESS;


--
-- SEARCH_AUTH_USER  (Synonym) 
--
CREATE SYNONYM SEARCH_AUTH_USER FOR SEARCHAPP.SEARCH_AUTH_USER;


--
-- SEARCH_AUTH_USER_SEC_ACCESS  (Synonym) 
--
CREATE SYNONYM SEARCH_AUTH_USER_SEC_ACCESS FOR SEARCHAPP.SEARCH_AUTH_USER_SEC_ACCESS;


--
-- SEARCH_AUTH_USER_SEC_ACCESS_V  (Synonym) 
--
CREATE SYNONYM SEARCH_AUTH_USER_SEC_ACCESS_V FOR SEARCHAPP.SEARCH_AUTH_USER_SEC_ACCESS_V;


--
-- SEARCH_BIO_MKR_CORREL_FAST_MV  (Synonym) 
--
CREATE SYNONYM SEARCH_BIO_MKR_CORREL_FAST_MV FOR SEARCHAPP.SEARCH_BIO_MKR_CORREL_FAST_MV;


--
-- SEARCH_BIO_MKR_CORREL_FST_VIEW  (Synonym) 
--
CREATE SYNONYM SEARCH_BIO_MKR_CORREL_FST_VIEW FOR SEARCHAPP.SEARCH_BIO_MKR_CORREL_FST_VIEW;


--
-- SEARCH_BIO_MKR_CORREL_VIEW  (Synonym) 
--
CREATE SYNONYM SEARCH_BIO_MKR_CORREL_VIEW FOR SEARCHAPP.SEARCH_BIO_MKR_CORREL_VIEW;


--
-- SEARCH_CATEGORIES  (Synonym) 
--
CREATE SYNONYM SEARCH_CATEGORIES FOR SEARCHAPP.SEARCH_CATEGORIES;


--
-- SEARCH_CUSTOM_FILTER  (Synonym) 
--
CREATE SYNONYM SEARCH_CUSTOM_FILTER FOR SEARCHAPP.SEARCH_CUSTOM_FILTER;


--
-- SEARCH_CUSTOM_FILTER_ITEM  (Synonym) 
--
CREATE SYNONYM SEARCH_CUSTOM_FILTER_ITEM FOR SEARCHAPP.SEARCH_CUSTOM_FILTER_ITEM;


--
-- SEARCH_GENE_SIGNATURE  (Synonym) 
--
CREATE SYNONYM SEARCH_GENE_SIGNATURE FOR SEARCHAPP.SEARCH_GENE_SIGNATURE;


--
-- SEARCH_GENE_SIGNATURE_ITEM  (Synonym) 
--
CREATE SYNONYM SEARCH_GENE_SIGNATURE_ITEM FOR SEARCHAPP.SEARCH_GENE_SIGNATURE_ITEM;


--
-- SEARCH_GENE_SIG_FILE_SCHEMA  (Synonym) 
--
CREATE SYNONYM SEARCH_GENE_SIG_FILE_SCHEMA FOR SEARCHAPP.SEARCH_GENE_SIG_FILE_SCHEMA;


--
-- SEARCH_KEYWORD  (Synonym) 
--
CREATE SYNONYM SEARCH_KEYWORD FOR SEARCHAPP.SEARCH_KEYWORD;


--
-- SEARCH_KEYWORD_TERM  (Synonym) 
--
CREATE SYNONYM SEARCH_KEYWORD_TERM FOR SEARCHAPP.SEARCH_KEYWORD_TERM;


--
-- SEARCH_REQUEST_MAP  (Synonym) 
--
CREATE SYNONYM SEARCH_REQUEST_MAP FOR SEARCHAPP.SEARCH_REQUEST_MAP;


--
-- SEARCH_ROLE  (Synonym) 
--
CREATE SYNONYM SEARCH_ROLE FOR SEARCHAPP.SEARCH_ROLE;


--
-- SEARCH_ROLE_AUTH_USER  (Synonym) 
--
CREATE SYNONYM SEARCH_ROLE_AUTH_USER FOR SEARCHAPP.SEARCH_ROLE_AUTH_USER;


--
-- SEARCH_SECURE_OBJECT  (Synonym) 
--
CREATE SYNONYM SEARCH_SECURE_OBJECT FOR SEARCHAPP.SEARCH_SECURE_OBJECT;


--
-- SEARCH_SECURE_OBJECT_PATH  (Synonym) 
--
CREATE SYNONYM SEARCH_SECURE_OBJECT_PATH FOR SEARCHAPP.SEARCH_SECURE_OBJECT_PATH;


--
-- SEARCH_SEC_ACCESS_LEVEL  (Synonym) 
--
CREATE SYNONYM SEARCH_SEC_ACCESS_LEVEL FOR SEARCHAPP.SEARCH_SEC_ACCESS_LEVEL;


--
-- SEARCH_TAXONOMY  (Synonym) 
--
CREATE SYNONYM SEARCH_TAXONOMY FOR SEARCHAPP.SEARCH_TAXONOMY;


--
-- SEARCH_TAXONOMY_LEVEL3  (Synonym) 
--
CREATE SYNONYM SEARCH_TAXONOMY_LEVEL3 FOR SEARCHAPP.SEARCH_TAXONOMY_LEVEL3;


--
-- SEARCH_TAXONOMY_LEVEL4  (Synonym) 
--
CREATE SYNONYM SEARCH_TAXONOMY_LEVEL4 FOR SEARCHAPP.SEARCH_TAXONOMY_LEVEL4;


--
-- SEARCH_TAXONOMY_LEVEL5  (Synonym) 
--
CREATE SYNONYM SEARCH_TAXONOMY_LEVEL5 FOR SEARCHAPP.SEARCH_TAXONOMY_LEVEL5;


--
-- SEARCH_TAXONOMY_LINEAGE  (Synonym) 
--
CREATE SYNONYM SEARCH_TAXONOMY_LINEAGE FOR SEARCHAPP.SEARCH_TAXONOMY_LINEAGE;


--
-- SEARCH_TAXONOMY_RELS  (Synonym) 
--
CREATE SYNONYM SEARCH_TAXONOMY_RELS FOR SEARCHAPP.SEARCH_TAXONOMY_RELS;


--
-- SEARCH_TAXONOMY_TERMS_CATS  (Synonym) 
--
CREATE SYNONYM SEARCH_TAXONOMY_TERMS_CATS FOR SEARCHAPP.SEARCH_TAXONOMY_TERMS_CATS;


--
-- SEARCH_USER_FEEDBACK  (Synonym) 
--
CREATE SYNONYM SEARCH_USER_FEEDBACK FOR SEARCHAPP.SEARCH_USER_FEEDBACK;


--
-- SEQ_AMAPP_DATA_ID  (Synonym) 
--
CREATE SYNONYM SEQ_AMAPP_DATA_ID FOR AMAPP.SEQ_AMAPP_DATA_ID;


--
-- SEQ_ASSAY_ID  (Synonym) 
--
CREATE SYNONYM SEQ_ASSAY_ID FOR DEAPP.SEQ_ASSAY_ID;


--
-- SEQ_BIO_DATA_FACT_ID  (Synonym) 
--
CREATE SYNONYM SEQ_BIO_DATA_FACT_ID FOR BIOMART.SEQ_BIO_DATA_FACT_ID;


--
-- SEQ_BIO_DATA_ID  (Synonym) 
--
CREATE SYNONYM SEQ_BIO_DATA_ID FOR BIOMART.SEQ_BIO_DATA_ID;


--
-- SEQ_CLINICAL_TRIAL_DESIGN_ID  (Synonym) 
--
CREATE SYNONYM SEQ_CLINICAL_TRIAL_DESIGN_ID FOR BIOMART.SEQ_CLINICAL_TRIAL_DESIGN_ID;


--
-- SEQ_CONCEPT_CODE  (Synonym) 
--
CREATE SYNONYM SEQ_CONCEPT_CODE FOR I2B2METADATA.SEQ_CONCEPT_CODE;


--
-- SEQ_DATA_ID  (Synonym) 
--
CREATE SYNONYM SEQ_DATA_ID FOR DEAPP.SEQ_DATA_ID;


--
-- SEQ_ETL_ID  (Synonym) 
--
CREATE SYNONYM SEQ_ETL_ID FOR TM_LZ.SEQ_ETL_ID;


--
-- SEQ_I2B2_DATA_ID  (Synonym) 
--
CREATE SYNONYM SEQ_I2B2_DATA_ID FOR I2B2METADATA.SEQ_I2B2_DATA_ID;


--
-- SEQ_PATIENT_NUM  (Synonym) 
--
CREATE SYNONYM SEQ_PATIENT_NUM FOR I2B2DEMODATA.SEQ_PATIENT_NUM;


--
-- SEQ_SEARCH_DATA_ID  (Synonym) 
--
CREATE SYNONYM SEQ_SEARCH_DATA_ID FOR SEARCHAPP.SEQ_SEARCH_DATA_ID;


--
-- SEQ_SEARCH_TAXONOMY_RELS_ID  (Synonym) 
--
CREATE SYNONYM SEQ_SEARCH_TAXONOMY_RELS_ID FOR SEARCHAPP.SEQ_SEARCH_TAXONOMY_RELS_ID;


--
-- SEQ_SEARCH_TAXONOMY_TERM_ID  (Synonym) 
--
CREATE SYNONYM SEQ_SEARCH_TAXONOMY_TERM_ID FOR SEARCHAPP.SEQ_SEARCH_TAXONOMY_TERM_ID;


--
-- SEQ_SUBJECT_REFERENCE  (Synonym) 
--
CREATE SYNONYM SEQ_SUBJECT_REFERENCE FOR I2B2DEMODATA.SEQ_SUBJECT_REFERENCE;


--
-- SETONT  (Synonym) 
--
CREATE SYNONYM SETONT FOR I2B2DEMODATA.SETONT;


--
-- SET_TYPE  (Synonym) 
--
CREATE SYNONYM SET_TYPE FOR I2B2DEMODATA.SET_TYPE;


--
-- SET_UPLOAD_STATUS  (Synonym) 
--
CREATE SYNONYM SET_UPLOAD_STATUS FOR I2B2DEMODATA.SET_UPLOAD_STATUS;


--
-- SOLR_KEYWORDS_LINEAGE  (Synonym) 
--
CREATE SYNONYM SOLR_KEYWORDS_LINEAGE FOR SEARCHAPP.SOLR_KEYWORDS_LINEAGE;


--
-- SOURCE_MASTER  (Synonym) 
--
CREATE SYNONYM SOURCE_MASTER FOR I2B2DEMODATA.SOURCE_MASTER;


--
-- SP_XTAB  (Synonym) 
--
CREATE SYNONYM SP_XTAB FOR I2B2DEMODATA.SP_XTAB;


--
-- SQ_UPLOADSTATUS_UPLOADID  (Synonym) 
--
CREATE SYNONYM SQ_UPLOADSTATUS_UPLOADID FOR I2B2DEMODATA.SQ_UPLOADSTATUS_UPLOADID;


--
-- SQ_UP_ENCDIM_ENCOUNTERNUM  (Synonym) 
--
CREATE SYNONYM SQ_UP_ENCDIM_ENCOUNTERNUM FOR I2B2DEMODATA.SQ_UP_ENCDIM_ENCOUNTERNUM;


--
-- SQ_UP_PATDIM_PATIENTNUM  (Synonym) 
--
CREATE SYNONYM SQ_UP_PATDIM_PATIENTNUM FOR I2B2DEMODATA.SQ_UP_PATDIM_PATIENTNUM;


--
-- SUBSET  (Synonym) 
--
CREATE SYNONYM SUBSET FOR SEARCHAPP.SUBSET;


--
-- TABLE_ACCESS  (Synonym) 
--
CREATE SYNONYM TABLE_ACCESS FOR I2B2SAMPLEDATA.TABLE_ACCESS;


--
-- TIMERS  (Synonym) 
--
CREATE SYNONYM TIMERS FOR I2B2HIVE.TIMERS;


--
-- TMP_ANALYSIS_DATA_TEA_RANK  (Synonym) 
--
CREATE SYNONYM TMP_ANALYSIS_DATA_TEA_RANK FOR BIOMART.TMP_ANALYSIS_DATA_TEA_RANK;


--
-- UPDATE_OBSERVATION_FACT  (Synonym) 
--
CREATE SYNONYM UPDATE_OBSERVATION_FACT FOR I2B2DEMODATA.UPDATE_OBSERVATION_FACT;


--
-- UPLOAD_STATUS  (Synonym) 
--
CREATE SYNONYM UPLOAD_STATUS FOR I2B2DEMODATA.UPLOAD_STATUS;


--
-- UTIL_GRANT_ALL  (Synonym) 
--
CREATE SYNONYM UTIL_GRANT_ALL FOR DEAPP.UTIL_GRANT_ALL;


--
-- VISIT_DIMENSION  (Synonym) 
--
CREATE SYNONYM VISIT_DIMENSION FOR I2B2DEMODATA.VISIT_DIMENSION;


--
-- WORKPLACE  (Synonym) 
--
CREATE SYNONYM WORKPLACE FOR I2B2WORKDATA.WORKPLACE;


--
-- WORKPLACE_ACCESS  (Synonym) 
--
CREATE SYNONYM WORKPLACE_ACCESS FOR I2B2WORKDATA.WORKPLACE_ACCESS;


--
-- WORK_DB_LOOKUP  (Synonym) 
--
CREATE SYNONYM WORK_DB_LOOKUP FOR I2B2HIVE.WORK_DB_LOOKUP;


--
-- PATIENT_SUBSET2  (Procedure) 
--
CREATE OR REPLACE PROCEDURE                "PATIENT_SUBSET2" (
  p_result_instance_id IN VARCHAR2,
  p_pathway IN VARCHAR2,
  p_refcur  OUT SYS_REFCURSOR) AS
  
  v_patients patients_tab;
  v_concept_cd concept_cd_tab;

BEGIN

SELECT patient_num BULK COLLECT INTO v_patients FROM (SELECT  
             DISTINCT a.patient_num
        FROM qt_patient_set_collection a, 
             qt_query_result_instance b, 
             qt_query_instance c, 
             qt_query_master d 
        WHERE a.result_instance_id = b.result_instance_id AND 
              b.query_instance_id = c.query_instance_id AND 
              c.query_master_id = d.query_master_id AND 
              b.result_instance_id = p_result_instance_id);
    
FOR record IN (SELECT SUBSTR(item_key,INSTR(item_key,'\',1,3)) AS concept_path  FROM (  
      SELECT extractValue(value(ik),'/item_key') item_key FROM (SELECT sys.xmltype.createXML(a.i2b2_request_xml) col 
        FROM qt_query_master a, 
             qt_query_instance b, 
             qt_query_result_instance c 
        WHERE a.query_master_id = b.query_master_id AND
              b.query_instance_id = c.query_instance_id AND 
              c.result_instance_id = p_result_instance_id) tab1,
              TABLE(xmlsequence(extract(col,'//ns4:request/query_definition/panel/item/item_key',                        
                                            'xmlns:ns4="http://www.i2b2.org/xsd/cell/crc/psm/1.1/"'))) ik))
LOOP                                            
   SELECT concept_cd BULK COLLECT INTO v_concept_cd FROM concept_dimension 
        WHERE concept_path like record.concept_path||'%';
END LOOP;
 
 
 FOR record IN (SELECT * FROM TABLE(CAST(v_concept_cd AS concept_cd_tab)))
 LOOP
 DBMS_OUTPUT.PUT_LINE(record.column_value);
 END LOOP;
 
OPEN p_refcur FOR
  SELECT DISTINCT a.probeset, a.gene_symbol, a.refseq, a.zscore, a.pvalue, b.patient_uid, a.assay_id
      FROM de_subject_assay_data a
      JOIN de_subject_sample_mapping b
        ON a.patient_id = b.patient_id
      JOIN de_pathway_gene c
        ON a.gene_symbol = c.gene_symbol
      JOIN de_pathway d
        ON d.id = c.pathway_id
      WHERE d.name = p_pathway
        AND b.patient_uid IN (SELECT * FROM TABLE(CAST(v_patients as patients_tab)))
        AND b.concept_code IN (CASE WHEN ( SELECT COUNT(*) FROM de_subject_sample_mapping 
                                       WHERE concept_code IN (SELECT * FROM TABLE(CAST(v_concept_cd AS concept_cd_tab)))) > 0 THEN
                                         (SELECT * FROM TABLE(CAST(v_concept_cd AS concept_cd_tab)))
                                       ELSE
                                         (SELECT concept_code FROM de_subject_sample_mapping)
                                      END);
                                         
END PATIENT_SUBSET2;

 
 
 
 
 
 
 
 
 
 
/

GRANT DELETE, INSERT, SELECT, UPDATE ON TOAD_PLAN_TABLE TO PUBLIC;